name: React CI

on:
  push:
    branches:
    - robin-cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 20

        - name: Install Dependencies
          run: npm install

            
        - name: Build
          run: npm run build

            
        - name: Test
          run: npm test