name: React CI

on:
  push:
    branches:
    - '!master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18.17.1

        - name: Install Dependencies
          run: cd coachapp-react && npm install

            
        - name: Build
          run: cd coachapp-react && npm run build

        - name: Test
          run: cd coachapp-react && npm test